export const APP_INIT = 'APP_INIT';

export const REQUEST_USERS = 'REQUEST_USERS';
export const REQUEST_USERS_SUCCESS = 'REQUEST_USERS_SUCCESS';
export const REQUEST_USERS_FAIL = 'REQUEST_USERS_FAIL';

export const REQUEST_USERS_NEXT = 'REQUEST_USERS_NEXT';
export const REQUEST_USERS_NEXT_SUCCESS = 'REQUEST_USERS_NEXT_SUCCESS';
export const REQUEST_USERS_NEXT_FAIL = 'REQUEST_USERS_NEXT_FAIL';

export const REQUEST_USER_FOLLOWERS = 'REQUEST_USER_FOLLOWERS';
export const REQUEST_USER_FOLLOWERS_SUCCESS = 'REQUEST_USER_FOLLOWERS_SUCCESS';
export const REQUEST_USER_FOLLOWERS_FAIL = 'REQUEST_USER_FOLLOWERS_FAIL';

export const REQUEST_USER_FOLLOWERS_NEXT = 'REQUEST_USER_FOLLOWERS_NEXT';
export const REQUEST_USER_FOLLOWERS_NEXT_SUCCESS = 'REQUEST_USER_FOLLOWERS_NEXT_SUCCESS';
export const REQUEST_USER_FOLLOWERS_NEXT_FAIL = 'REQUEST_USER_FOLLOWERS_NEXT_FAIL';

export const SELECT_USER = 'SELECT_USER';
